name: Airtable Lakeflow Connector
pipeline_type: WORKSPACE
libraries:
  - notebook:
      path: /Users/kaustav.paul@databricks.com/lakeflow-community-connectors/sources/airtable-connector/sdp_ingest/airtable_sdp_correct.py
catalog: kaustavpaul_demo
target: airtable_connector
continuous: false
development: true
photon: true
channel: CURRENT
serverless: true

